### ISSUE TITLE
运行没有引入beike_aspectd的项目,运行出错

### ISSUE THREAD

**Issue by zhangshuqi** [LianjiaTech/Beike_AspectD#33]
[flutter_02.log](https://github.com/LianjiaTech/Beike_AspectD/files/12102984/flutter_02.log)
报错日志如文件所示

**Comment by zhangshuqi** [comment]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --track-widget-creation --device-id=7505006f --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart

## exception

StateError: Bad state: No element

```
#0      ListBase.firstWhere (dart:collection/list.dart:132:5)
#1      AspectdHook.getPackagePathFromConfig (package:flutter_tools/src/aop/aspectd.dart:40:70)
<asynchronous suspension>
#2      AspectdHook.enableAspectd (package:flutter_tools/src/aop/aspectd.dart:102:9)
<asynchronous suspension>
#3      DefaultResidentCompiler._compile (package:flutter_tools/src/compile.dart:755:5)
<asynchronous suspension>
#4      _CompilationRequest.run (package:flutter_tools/src/compile.dart:381:24)
<asynchronous suspension>
#5      DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:738:9)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.2.1 22D68 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.10.5 on channel stable at /Users/zhangshuqi/flutter3.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (5 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/zhangshuqi/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/zhangshuqi/Library/Android/sdk
    • Java binary at: /Applications/AndroidStudio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/AndroidStudio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • MIX 2S (mobile)    • 7505006f                  • android-arm64  • Android 10 (API 29)
    • iPhone123 (mobile) • 00008110-001E11193A52801E • ios            • iOS 16.3.1 20D67
    • macOS (desktop)    • macos                     • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 114.0.5735.198

[!] Network resources
    ✗ An HTTP error occurred while checking "https://github.com/": Connection closed before full header was received

! Doctor found issues in 1 category.
```

**Comment by zhangshuqi** [comment]
多次尝试后 发现将aop_config.yaml文件复制到flutter项目下就可以运行 即使flutter项目没有集成aspectd.

**Comment by tanzhihao1qaz** [comment]
我不集成也能正常运行哦
