### ISSUE TITLE
泛型会报错

### ISSUE THREAD

**Issue by LDouble** [LianjiaTech/Beike_AspectD#4]
```
  T testGenericType<T>(Map<T, dynamic> param) {
    return null;
  }

```
如果去切泛型函数的话，就会抛出这个错误
```
[+2599 ms] [+2561 ms] Unhandled exception:
[        ]            Invalid argument(s): Type parameter TypeParameter(T) is not indexed
[        ]            #0      TypeParameterIndexer.[] (package:kernel/binary/ast_to_binary.dart:2871:8)
[        ]            #1      BinaryPrinter.visitTypeParameterType (package:kernel/binary/ast_to_binary.dart:2397:38)
[        ]            #2      TypeParameterType.accept (package:kernel/ast.dart:11472:42)
[        ]            #3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:420:10)
[        ]            #4      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:331:7)
[        ]            #5      BinaryPrinter.visitInterfaceType (package:kernel/binary/ast_to_binary.dart:2295:7)
[        ]            #6      InterfaceType.accept (package:kernel/ast.dart:10703:42)
[        ]            #7      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:420:
```

**Comment by soloxiao** [comment]
> ```
>   T testGenericType<T>(Map<T, dynamic> param) {
>     return null;
>   }
> ```
> 
> 
>      
>   
> 
> 如果去切泛型函数的话，就会抛出这个错误
> 
> 
> ```
> [+2599 ms] [+2561 ms] Unhandled exception:
> [        ]            Invalid argument(s): Type parameter TypeParameter(T) is not indexed
> [        ]            #0      TypeParameterIndexer.[] (package:kernel/binary/ast_to_binary.dart:2871:8)
> [        ]            #1      BinaryPrinter.visitTypeParameterType (package:kernel/binary/ast_to_binary.dart:2397:38)
> [        ]            #2      TypeParameterType.accept (package:kernel/ast.dart:11472:42)
> [        ]            #3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:420:10)
> [        ]            #4      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:331:7)
> [        ]            #5      BinaryPrinter.visitInterfaceType (package:kernel/binary/ast_to_binary.dart:2295:7)
> [        ]            #6      InterfaceType.accept (package:kernel/ast.dart:10703:42)
> [        ]            #7      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:420:
> ```

具体的hook代码发一下吧
