### ISSUE TITLE
3.10.5版本按照步骤引用成功，但运行工程时报错

### ISSUE THREAD

**Issue by alicehyxx** [LianjiaTech/Beike_AspectD#40]
Unhandled exception:
Crash when compiling:
Null check operator used on a null value

#0      AopAddImplTransformer._filterAopItemInfo (file:///Users/solo/Project/beike_aspectd_opensource/inner/transformer/plugins/aop/beike_transformer/aop_addimpl_transformer.dart:181:50)
#1      AopAddImplTransformer.visitClass (file:///Users/solo/Project/beike_aspectd_opensource/inner/transformer/plugins/aop/beike_transformer/aop_addimpl_transformer.dart:25:32)
#2      Class.accept (package:kernel/ast.dart:1481:38)
#3      visitList (package:kernel/ast.dart:15225:14)
#4      Library.visitChildren (package:kernel/ast.dart:598:5)
#5      AopAddImplTransformer.visitLibrary (file:///Users/solo/Project/beike_aspectd_opensource/inner/transformer/plugins/aop/beike_transformer/aop_addimpl_transformer.dart:17:10)
#6      AopWrapperTransformer.transform (file:///Users/solo/Project/beike_aspectd_opensource/inner/transformer/plugins/aop/aop_transformer_wrapper.dart:138:31)
#7      FlutterTarget.performPreConstantEvaluationTransformations (package:vm/target/flutter.dart:72:40)
#8      KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1518:19)
#9      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:638:7)
<asynchronous suspension>
#10     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#11     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:413:23)
<asynchronous suspension>
#12     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:75:50)
<asynchronous suspension>
#13     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:595:11)
<asynchronous suspension>
#14     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1308:11)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.

我看着错误，感觉是切片的代码没有针对空安全做好适配。或是我配置的问题？

**Comment by alicehyxx** [comment]
有大佬帮看看这个问题么？这个解决不了，3.10.5版本切片完全就用不了了
