### ISSUE TITLE
3.3.10 下debug模式下编译错误

### ISSUE THREAD

**Issue by Zivwu** [LianjiaTech/Beike_AspectD#41]
[+8622 ms] Unhandled exception:
[        ] root::package:beike_aspectd/src/plugins/aop/annotation/pointcut.dart::PointCut::@methods::aop_stub_0 is already bound to Reference to
           package:beike_aspectd/src/plugins/aop/annotation/pointcut.dart::PointCut::@methods::aop_stub_0 with node PointCut.aop_stub_0 (Procedure:75096), trying to bind
to
           Reference to PointCut.aop_stub_0 with node PointCut.aop_stub_0 (Procedure:2431202)
[        ] #0      CanonicalName.bindTo (package:kernel/canonical_name.dart:237:7)
[        ] #1      Procedure.bindCanonicalNames (package:kernel/ast.dart:3038:40)
[        ] #2      Class.ensureCanonicalNames (package:kernel/ast.dart:1270:21)
[        ] #3      Library.ensureCanonicalNames (package:kernel/ast.dart:514:18)
[        ] #4      Component.computeCanonicalNamesForLibrary (package:kernel/ast.dart:14028:13)
[        ] #5      Component.computeCanonicalNames (package:kernel/ast.dart:13991:7)
[        ] #6      sortComponent (package:vm/kernel_front_end.dart:738:13)
[        ] #7      FrontendCompiler.writeDillFile (package:frontend_server/frontend_server.dart:736:5)
[        ] #8      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:615:13)
[        ] <asynchronous suspension>
[        ] #9      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1210:11)
[        ] <asynchronous suspension>
[  +80 ms] the Dart compiler exited unexpectedly.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:835:13)
           #2      _rootRun (dart:async/zone.dart:1383:47)
           #3      _CustomZone.run (dart:async/zone.dart:1293:19)
           #4      _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
           #5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #8      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #9      _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #10     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #11     _LineSplitterSink.close (dart:convert/line_splitter.dart:154:11)
           #12     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #13     _rootRun (dart:async/zone.dart:1383:47)
           #14     _CustomZone.run (dart:async/zone.dart:1293:19)
           #15     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
           #16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #21     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
           #24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #25     _rootRun (dart:async/zone.dart:1383:47)
           #26     _CustomZone.run (dart:async/zone.dart:1293:19)
           #27     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
           #28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #31     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:782:19)
           #32     _StreamController._closeUnchecked (dart:async/stream_controller.dart:637:7)
           #33     _StreamController.close (dart:async/stream_controller.dart:630:5)
           #34     _Socket._onData (dart:io-patch/socket_patch.dart:2331:21)
           #35     _rootRunUnary (dart:async/zone.dart:1407:13)
           #36     _CustomZone.runUnary (dart:async/zone.dart:1300:19)
           #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
           #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
           #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
           #41     _StreamController._add (dart:async/stream_controller.dart:648:7)
           #42     _StreamController.add (dart:async/stream_controller.dart:596:5)
           #43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1856:35)
           #44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1315:18)
           #45     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
           #48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
           
           
[   +6 ms] ensureAnalyticsSent: 1ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] the Dart compiler exited unexpectedly.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:835:13)
           #2      _rootRun (dart:async/zone.dart:1383:47)
           #3      _CustomZone.run (dart:async/zone.dart:1293:19)
           #4      _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
           #5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #8      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #9      _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #10     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #11     _LineSplitterSink.close (dart:convert/line_splitter.dart:154:11)
           #12     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #13     _rootRun (dart:async/zone.dart:1383:47)
           #14     _CustomZone.run (dart:async/zone.dart:1293:19)
           #15     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
           #16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #21     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
           #24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #25     _rootRun (dart:async/zone.dart:1383:47)
           #26     _CustomZone.run (dart:async/zone.dart:1293:19)
           #27     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
           #28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
           #29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
           #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #31     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:782:19)
           #32     _StreamController._closeUnchecked (dart:async/stream_controller.dart:637:7)
           #33     _StreamController.close (dart:async/stream_controller.dart:630:5)
           #34     _Socket._onData (dart:io-patch/socket_patch.dart:2331:21)
           #35     _rootRunUnary (dart:async/zone.dart:1407:13)
           #36     _CustomZone.runUnary (dart:async/zone.dart:1300:19)
           #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
           #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
           #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
           #41     _StreamController._add (dart:async/stream_controller.dart:648:7)
           #42     _StreamController.add (dart:async/stream_controller.dart:596:5)
           #43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1856:35)
           #44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1315:18)
           #45     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
           #48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
           
           
[   +3 ms] ensureAnalyticsSent: 0ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
mingdeMac-mini:flutter_study ziv$

**Comment by Zivwu** [comment]
具体代码为:<img width="1088" alt="image" src="https://github.com/LianjiaTech/Beike_AspectD/assets/20123837/7699a62f-719a-41df-88c8-cb57dd91d298">
在profile 和release 是正常的

**Comment by Zivwu** [comment]
flutter clean 后重新编译
